### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by handicraftsman** [jonnor/libsoup#1]
````
Could not listen on address 192.168.0.100, port 8080
````
I see this error in my vFrame program ( https://github.com/vSoftTeam/vFrame ). But i don't see any wrong code. Sources with soup server - framework/http_server.vala

**Comment by handicraftsman** [comment]
Also i see:
````
(exec:4253): libsoup-CRITICAL **: soup_socket_listen: assertion 'priv->gsock == NULL' failed
````

**Comment by jonnor** [comment]
@handicraftsman Hi. WebSocket support is upstream in libsoup since version 2.50.0. You should use that instead of this repository. https://wiki.gnome.org/action/show/Projects/libsoup?action=show&redirect=LibSoup

**Comment by handicraftsman** [comment]
Sorry, but i am developing on debian sid, which will come to ubuntu 16.04. Users need working software, not broken deps and not build problems.

**Comment by jonnor** [comment]
I agree with that. But I am not the developer of libsoup, and can unfortunately not help you. I had a brief look over the code and could not find anything obvious. I recommend that you contact the libsoup developers, through one of the communication channels at>
https://wiki.gnome.org/action/show/Projects/libsoup?action=show&redirect=LibSoup
